name: 'Env template'
description: 'Replaces ${TOKENS} with environment variables in file.'
author: 'Vadim Vafin <vafinvr@ya.ru>'
branding:
  icon: 'align-left'
  color: 'purple'
inputs:
  filename:
    description: 'File for the replacement'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
